ALTER TABLE "CardUsageHourly" ADD COLUMN "cacheWrite5mTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CardUsageHourly" ADD COLUMN "cacheWrite1hTokens" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CardUsageHourly" ADD COLUMN "apiValueUsd" REAL NOT NULL DEFAULT 0;
ALTER TABLE "CardUsageHourly" ADD COLUMN "apiPricedRequests" INTEGER NOT NULL DEFAULT 0;
