// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ActivateCard(arg1:string):Promise<string>;

export function AddPoolAccount(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function BrowseForPath(arg1:string):Promise<string>;

export function CheckForUpdate():Promise<Record<string, any>>;

export function ClearLogs():Promise<boolean>;

export function ClearStats():Promise<boolean>;

export function DownloadUpdate():Promise<void>;

export function GetAnnouncement():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<main.Config>;

export function GetDetectedPaths():Promise<main.DetectedPaths>;

export function GetIDEStatus():Promise<main.IDEStatus>;

export function GetLogs():Promise<Array<string>>;

export function GetPoolAccounts():Promise<Array<main.AccountInfo>>;

export function GetPoolMode():Promise<string>;

export function GetPoolStatus():Promise<Record<string, any>>;

export function GetStats():Promise<Record<string, any>>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function InjectSelected(arg1:Array<string>):Promise<string>;

export function IsHubRunningCheck():Promise<boolean>;

export function IsIDERunningCheck():Promise<boolean>;

export function OAuthLogin(arg1:string):Promise<Record<string, any>>;

export function RemovePoolAccount(arg1:number):Promise<Record<string, any>>;

export function RestartProxy():Promise<void>;

export function RestartToUpdate():Promise<void>;

export function RestoreSelected(arg1:Array<string>):Promise<string>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetPoolMode(arg1:string):Promise<Record<string, any>>;

export function TogglePoolAccount(arg1:number,arg2:boolean):Promise<Record<string, any>>;
