// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateCard(arg1) {
  return window['go']['main']['App']['ActivateCard'](arg1);
}

export function AddPoolAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddPoolAccount'](arg1, arg2, arg3);
}

export function BrowseForPath(arg1) {
  return window['go']['main']['App']['BrowseForPath'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearStats() {
  return window['go']['main']['App']['ClearStats']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetAnnouncement() {
  return window['go']['main']['App']['GetAnnouncement']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetectedPaths() {
  return window['go']['main']['App']['GetDetectedPaths']();
}

export function GetIDEStatus() {
  return window['go']['main']['App']['GetIDEStatus']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPoolAccounts() {
  return window['go']['main']['App']['GetPoolAccounts']();
}

export function GetPoolMode() {
  return window['go']['main']['App']['GetPoolMode']();
}

export function GetPoolStatus() {
  return window['go']['main']['App']['GetPoolStatus']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function InjectSelected(arg1) {
  return window['go']['main']['App']['InjectSelected'](arg1);
}

export function IsHubRunningCheck() {
  return window['go']['main']['App']['IsHubRunningCheck']();
}

export function IsIDERunningCheck() {
  return window['go']['main']['App']['IsIDERunningCheck']();
}

export function OAuthLogin(arg1) {
  return window['go']['main']['App']['OAuthLogin'](arg1);
}

export function RemovePoolAccount(arg1) {
  return window['go']['main']['App']['RemovePoolAccount'](arg1);
}

export function RestartProxy() {
  return window['go']['main']['App']['RestartProxy']();
}

export function RestartToUpdate() {
  return window['go']['main']['App']['RestartToUpdate']();
}

export function RestoreSelected(arg1) {
  return window['go']['main']['App']['RestoreSelected'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetPoolMode(arg1) {
  return window['go']['main']['App']['SetPoolMode'](arg1);
}

export function TogglePoolAccount(arg1, arg2) {
  return window['go']['main']['App']['TogglePoolAccount'](arg1, arg2);
}
