// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateCode(arg1) {
  return window['go']['main']['App']['ActivateCode'](arg1);
}

export function BrowseForPath(arg1) {
  return window['go']['main']['App']['BrowseForPath'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearStats() {
  return window['go']['main']['App']['ClearStats']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetAccountState() {
  return window['go']['main']['App']['GetAccountState']();
}

export function GetAnnouncement() {
  return window['go']['main']['App']['GetAnnouncement']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCodexRelayConfig() {
  return window['go']['main']['App']['GetCodexRelayConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetectedPaths() {
  return window['go']['main']['App']['GetDetectedPaths']();
}

export function GetFaqData() {
  return window['go']['main']['App']['GetFaqData']();
}

export function GetIDEStatus() {
  return window['go']['main']['App']['GetIDEStatus']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetReferralInfo() {
  return window['go']['main']['App']['GetReferralInfo']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function HeartbeatCheck() {
  return window['go']['main']['App']['HeartbeatCheck']();
}

export function InjectSelected(arg1) {
  return window['go']['main']['App']['InjectSelected'](arg1);
}

export function InstallStandaloneClaude() {
  return window['go']['main']['App']['InstallStandaloneClaude']();
}

export function IsHubRunningCheck() {
  return window['go']['main']['App']['IsHubRunningCheck']();
}

export function IsIDERunningCheck() {
  return window['go']['main']['App']['IsIDERunningCheck']();
}

export function OpenCACertForTrust() {
  return window['go']['main']['App']['OpenCACertForTrust']();
}

export function OpenSystemPermissionSettings() {
  return window['go']['main']['App']['OpenSystemPermissionSettings']();
}

export function RefreshQuota() {
  return window['go']['main']['App']['RefreshQuota']();
}

export function RestartProxy() {
  return window['go']['main']['App']['RestartProxy']();
}

export function RestartToUpdate() {
  return window['go']['main']['App']['RestartToUpdate']();
}

export function RestoreSelected(arg1) {
  return window['go']['main']['App']['RestoreSelected'](arg1);
}

export function SaveCodexRelayConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveCodexRelayConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetClaudeDesktopMockLogin(arg1) {
  return window['go']['main']['App']['SetClaudeDesktopMockLogin'](arg1);
}

export function SetSubscriptionPriority(arg1, arg2) {
  return window['go']['main']['App']['SetSubscriptionPriority'](arg1, arg2);
}

export function UserLogin(arg1, arg2) {
  return window['go']['main']['App']['UserLogin'](arg1, arg2);
}

export function UserLogout() {
  return window['go']['main']['App']['UserLogout']();
}
