// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateCode(arg1) {
  return window['go']['main']['App']['ActivateCode'](arg1);
}

export function BrowseForPath(arg1) {
  return window['go']['main']['App']['BrowseForPath'](arg1);
}

export function CheckForUpdate() {
  return window['go']['main']['App']['CheckForUpdate']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearStats() {
  return window['go']['main']['App']['ClearStats']();
}

export function DownloadUpdate() {
  return window['go']['main']['App']['DownloadUpdate']();
}

export function GetAccountState() {
  return window['go']['main']['App']['GetAccountState']();
}

export function GetAnnouncement() {
  return window['go']['main']['App']['GetAnnouncement']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetCodexRelayConfig() {
  return window['go']['main']['App']['GetCodexRelayConfig']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDetectedPaths() {
  return window['go']['main']['App']['GetDetectedPaths']();
}

export function GetFaqData() {
  return window['go']['main']['App']['GetFaqData']();
}

export function GetIDEStatus() {
  return window['go']['main']['App']['GetIDEStatus']();
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetReferralInfo() {
  return window['go']['main']['App']['GetReferralInfo']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetUpdateStatus() {
  return window['go']['main']['App']['GetUpdateStatus']();
}

export function HeartbeatCheck() {
  return window['go']['main']['App']['HeartbeatCheck']();
}

export function InjectSelected(arg1) {
  return window['go']['main']['App']['InjectSelected'](arg1);
}

export function InstallStandaloneClaude() {
  return window['go']['main']['App']['InstallStandaloneClaude']();
}

export function IsHubRunningCheck() {
  return window['go']['main']['App']['IsHubRunningCheck']();
}

export function IsIDERunningCheck() {
  return window['go']['main']['App']['IsIDERunningCheck']();
}

export function LocalAntigravityGatewayStart() {
  return window['go']['main']['App']['LocalAntigravityGatewayStart']();
}

export function LocalAntigravityGatewayStatus() {
  return window['go']['main']['App']['LocalAntigravityGatewayStatus']();
}

export function LocalAntigravityGatewayStop() {
  return window['go']['main']['App']['LocalAntigravityGatewayStop']();
}

export function LocalAntigravityStats() {
  return window['go']['main']['App']['LocalAntigravityStats']();
}

export function LocalAntigravityWakeupConfig() {
  return window['go']['main']['App']['LocalAntigravityWakeupConfig']();
}

export function LocalAntigravityWakeupHistory() {
  return window['go']['main']['App']['LocalAntigravityWakeupHistory']();
}

export function LocalAntigravityWakeupRunNow() {
  return window['go']['main']['App']['LocalAntigravityWakeupRunNow']();
}

export function LocalCodexStats() {
  return window['go']['main']['App']['LocalCodexStats']();
}

export function LocalCodexWakeupConfig() {
  return window['go']['main']['App']['LocalCodexWakeupConfig']();
}

export function LocalCodexWakeupHistory() {
  return window['go']['main']['App']['LocalCodexWakeupHistory']();
}

export function LocalCodexWakeupRunNow() {
  return window['go']['main']['App']['LocalCodexWakeupRunNow']();
}

export function LocalDeleteAccount(arg1) {
  return window['go']['main']['App']['LocalDeleteAccount'](arg1);
}

export function LocalDeleteAccounts(arg1) {
  return window['go']['main']['App']['LocalDeleteAccounts'](arg1);
}

export function LocalExportAntigravityAccounts(arg1) {
  return window['go']['main']['App']['LocalExportAntigravityAccounts'](arg1);
}

export function LocalExportCodexAccounts(arg1) {
  return window['go']['main']['App']['LocalExportCodexAccounts'](arg1);
}

export function LocalGatewayStart() {
  return window['go']['main']['App']['LocalGatewayStart']();
}

export function LocalGatewayStatus() {
  return window['go']['main']['App']['LocalGatewayStatus']();
}

export function LocalGatewayStop() {
  return window['go']['main']['App']['LocalGatewayStop']();
}

export function LocalGetAntigravitySource() {
  return window['go']['main']['App']['LocalGetAntigravitySource']();
}

export function LocalGetCodexSource() {
  return window['go']['main']['App']['LocalGetCodexSource']();
}

export function LocalImportAntigravityFromJSON(arg1) {
  return window['go']['main']['App']['LocalImportAntigravityFromJSON'](arg1);
}

export function LocalImportCodexFromJSON(arg1) {
  return window['go']['main']['App']['LocalImportCodexFromJSON'](arg1);
}

export function LocalInstanceCreate(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['LocalInstanceCreate'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function LocalInstanceDelete(arg1) {
  return window['go']['main']['App']['LocalInstanceDelete'](arg1);
}

export function LocalInstanceLaunch(arg1) {
  return window['go']['main']['App']['LocalInstanceLaunch'](arg1);
}

export function LocalInstanceList(arg1) {
  return window['go']['main']['App']['LocalInstanceList'](arg1);
}

export function LocalInstanceStop(arg1) {
  return window['go']['main']['App']['LocalInstanceStop'](arg1);
}

export function LocalInstanceUpdate(arg1) {
  return window['go']['main']['App']['LocalInstanceUpdate'](arg1);
}

export function LocalListAntigravityAccounts() {
  return window['go']['main']['App']['LocalListAntigravityAccounts']();
}

export function LocalListCodexAccounts() {
  return window['go']['main']['App']['LocalListCodexAccounts']();
}

export function LocalSetAntigravityPriority(arg1) {
  return window['go']['main']['App']['LocalSetAntigravityPriority'](arg1);
}

export function LocalSetAntigravitySource(arg1) {
  return window['go']['main']['App']['LocalSetAntigravitySource'](arg1);
}

export function LocalSetAntigravityWakeupConfig(arg1, arg2) {
  return window['go']['main']['App']['LocalSetAntigravityWakeupConfig'](arg1, arg2);
}

export function LocalSetCodexPriority(arg1) {
  return window['go']['main']['App']['LocalSetCodexPriority'](arg1);
}

export function LocalSetCodexSource(arg1) {
  return window['go']['main']['App']['LocalSetCodexSource'](arg1);
}

export function LocalSetCodexWakeupConfig(arg1, arg2) {
  return window['go']['main']['App']['LocalSetCodexWakeupConfig'](arg1, arg2);
}

export function LocalSetPoolEnabled(arg1, arg2) {
  return window['go']['main']['App']['LocalSetPoolEnabled'](arg1, arg2);
}

export function LocalStartAntigravityLogin() {
  return window['go']['main']['App']['LocalStartAntigravityLogin']();
}

export function LocalStartCodexLogin() {
  return window['go']['main']['App']['LocalStartCodexLogin']();
}

export function LocalWaitAntigravityLogin(arg1) {
  return window['go']['main']['App']['LocalWaitAntigravityLogin'](arg1);
}

export function LocalWaitCodexLogin(arg1) {
  return window['go']['main']['App']['LocalWaitCodexLogin'](arg1);
}

export function OpenCACertForTrust() {
  return window['go']['main']['App']['OpenCACertForTrust']();
}

export function OpenSystemPermissionSettings() {
  return window['go']['main']['App']['OpenSystemPermissionSettings']();
}

export function RefreshQuota() {
  return window['go']['main']['App']['RefreshQuota']();
}

export function RestartProxy() {
  return window['go']['main']['App']['RestartProxy']();
}

export function RestartToUpdate() {
  return window['go']['main']['App']['RestartToUpdate']();
}

export function RestoreSelected(arg1) {
  return window['go']['main']['App']['RestoreSelected'](arg1);
}

export function SaveCodexRelayConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveCodexRelayConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetClaudeDesktopMockLogin(arg1) {
  return window['go']['main']['App']['SetClaudeDesktopMockLogin'](arg1);
}

export function SetSubscriptionPriority(arg1, arg2) {
  return window['go']['main']['App']['SetSubscriptionPriority'](arg1, arg2);
}

export function UserLogin(arg1, arg2) {
  return window['go']['main']['App']['UserLogin'](arg1, arg2);
}

export function UserLogout() {
  return window['go']['main']['App']['UserLogout']();
}
