// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {manager} from '../models';
import {hub} from '../models';
import {stats} from '../models';
import {wakeup} from '../models';
import {gatewaykeys} from '../models';
import {gateway} from '../models';
import {refreshcfg} from '../models';
import {instance} from '../models';

export function ActivateCode(arg1:string):Promise<Record<string, any>>;

export function BrowseForPath(arg1:string):Promise<string>;

export function CheckForUpdate():Promise<Record<string, any>>;

export function ClearLogs():Promise<boolean>;

export function ClearStats():Promise<boolean>;

export function DownloadUpdate():Promise<void>;

export function GetAccountState():Promise<Record<string, any>>;

export function GetAnnouncement():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetCodexRelayConfig():Promise<Record<string, any>>;

export function GetConfig():Promise<main.Config>;

export function GetDetectedPaths():Promise<main.DetectedPaths>;

export function GetFaqData():Promise<Record<string, any>>;

export function GetIDEStatus():Promise<main.IDEStatus>;

export function GetLogs():Promise<Array<string>>;

export function GetReferralInfo():Promise<Record<string, any>>;

export function GetStats():Promise<Record<string, any>>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function HeartbeatCheck():Promise<Record<string, any>>;

export function InjectSelected(arg1:Array<string>):Promise<string>;

export function InstallStandaloneClaude():Promise<void>;

export function IsHubRunningCheck():Promise<boolean>;

export function IsIDERunningCheck():Promise<boolean>;

export function LocalAddAntigravityApiKey(arg1:string,arg2:string,arg3:string):Promise<manager.AccountView>;

export function LocalAddAntigravityToken(arg1:string,arg2:string,arg3:string):Promise<manager.AccountView>;

export function LocalAddCodexApiKey(arg1:string,arg2:string,arg3:string):Promise<manager.AccountView>;

export function LocalAddCodexToken(arg1:string,arg2:string,arg3:string):Promise<manager.AccountView>;

export function LocalAntigravityGatewayStart():Promise<hub.GatewayStatus>;

export function LocalAntigravityGatewayStatus():Promise<hub.GatewayStatus>;

export function LocalAntigravityGatewayStop():Promise<void>;

export function LocalAntigravityStats():Promise<stats.Snapshot>;

export function LocalAntigravityWakeupConfig():Promise<wakeup.Config>;

export function LocalAntigravityWakeupHistory():Promise<Array<wakeup.RunEntry>>;

export function LocalAntigravityWakeupRunNow():Promise<Array<wakeup.RunEntry>>;

export function LocalClearGatewayStats():Promise<void>;

export function LocalCodexStats():Promise<stats.Snapshot>;

export function LocalCodexWakeupConfig():Promise<wakeup.Config>;

export function LocalCodexWakeupHistory():Promise<Array<wakeup.RunEntry>>;

export function LocalCodexWakeupRunNow():Promise<Array<wakeup.RunEntry>>;

export function LocalCreateGatewayKey(arg1:string):Promise<gatewaykeys.Key>;

export function LocalDeleteAccount(arg1:string):Promise<void>;

export function LocalDeleteAccounts(arg1:Array<string>):Promise<void>;

export function LocalDeleteGatewayKey(arg1:string):Promise<void>;

export function LocalExportAntigravityAccounts(arg1:Array<string>):Promise<string>;

export function LocalExportCodexAccounts(arg1:Array<string>):Promise<string>;

export function LocalGatewayConnTest():Promise<gateway.ConnTestResult>;

export function LocalGatewayStart():Promise<hub.GatewayStatus>;

export function LocalGatewayStatus():Promise<hub.GatewayStatus>;

export function LocalGatewayStop():Promise<void>;

export function LocalGetAntigravitySource():Promise<string>;

export function LocalGetCodexSource():Promise<string>;

export function LocalGetGatewayAccessScope():Promise<string>;

export function LocalGetRefreshConfig():Promise<refreshcfg.Config>;

export function LocalGetRoutingStrategy():Promise<string>;

export function LocalImportAntigravityAuthFiles(arg1:Array<string>):Promise<number>;

export function LocalImportAntigravityFromJSON(arg1:string):Promise<number>;

export function LocalImportCodexAuthFiles(arg1:Array<string>):Promise<number>;

export function LocalImportCodexFromJSON(arg1:string):Promise<number>;

export function LocalImportCodexFromLocal():Promise<number>;

export function LocalInstanceCreate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<instance.Profile>;

export function LocalInstanceDelete(arg1:string):Promise<void>;

export function LocalInstanceLaunch(arg1:string):Promise<void>;

export function LocalInstanceList(arg1:string):Promise<Array<instance.Profile>>;

export function LocalInstanceStop(arg1:string):Promise<void>;

export function LocalInstanceUpdate(arg1:instance.Profile):Promise<void>;

export function LocalListAntigravityAccounts():Promise<Array<manager.AccountView>>;

export function LocalListCodexAccounts():Promise<Array<manager.AccountView>>;

export function LocalListGatewayKeys():Promise<Array<gatewaykeys.Key>>;

export function LocalQueryGatewayLogs(arg1:number,arg2:number,arg3:string):Promise<stats.LogPage>;

export function LocalRefreshAccountQuota(arg1:string):Promise<void>;

export function LocalRefreshAllQuotas(arg1:string):Promise<number>;

export function LocalRenameAccount(arg1:string,arg2:string):Promise<void>;

export function LocalRotateGatewayKey(arg1:string):Promise<gatewaykeys.Key>;

export function LocalSetAccountNote(arg1:string,arg2:string):Promise<void>;

export function LocalSetAccountTags(arg1:string,arg2:Array<string>):Promise<void>;

export function LocalSetAntigravityPriority(arg1:string):Promise<void>;

export function LocalSetAntigravitySource(arg1:string):Promise<void>;

export function LocalSetAntigravityWakeupConfig(arg1:boolean,arg2:number):Promise<void>;

export function LocalSetCodexPriority(arg1:string):Promise<void>;

export function LocalSetCodexSource(arg1:string):Promise<void>;

export function LocalSetCodexWakeupConfig(arg1:boolean,arg2:number):Promise<void>;

export function LocalSetGatewayAccessScope(arg1:string):Promise<void>;

export function LocalSetGatewayPort(arg1:number):Promise<hub.GatewayStatus>;

export function LocalSetPoolEnabled(arg1:string,arg2:boolean):Promise<void>;

export function LocalSetRefreshConfig(arg1:number,arg2:number):Promise<refreshcfg.Config>;

export function LocalSetRoutingStrategy(arg1:string):Promise<void>;

export function LocalStartAntigravityLogin():Promise<string>;

export function LocalStartCodexLogin():Promise<string>;

export function LocalSyncAntigravityFromIDE():Promise<number>;

export function LocalWaitAntigravityLogin(arg1:string):Promise<manager.AccountView>;

export function LocalWaitCodexLogin(arg1:string):Promise<manager.AccountView>;

export function OpenCACertForTrust():Promise<void>;

export function OpenSystemPermissionSettings():Promise<void>;

export function RefreshQuota():Promise<void>;

export function RestartProxy():Promise<void>;

export function RestartToUpdate():Promise<void>;

export function RestoreSelected(arg1:Array<string>):Promise<string>;

export function SaveCodexRelayConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetClaudeDesktopMockLogin(arg1:boolean):Promise<boolean>;

export function SetSubscriptionPriority(arg1:string,arg2:number):Promise<void>;

export function UserLogin(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UserLogout():Promise<void>;
