// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {gatewaycfg} from '../models';
import {manager} from '../models';
import {aghistory} from '../models';
import {hub} from '../models';
import {stats} from '../models';
import {wakeup} from '../models';
import {accountgroups} from '../models';
import {codexbiz} from '../models';
import {sessionsync} from '../models';
import {gatewaykeys} from '../models';
import {economy} from '../models';
import {gateway} from '../models';
import {codexsettings} from '../models';
import {refreshcfg} from '../models';
import {modelprovider} from '../models';

export function ActivateCode(arg1:string):Promise<Record<string, any>>;

export function BrowseForPath(arg1:string):Promise<string>;

export function CheckForUpdate():Promise<Record<string, any>>;

export function ClearLogs():Promise<boolean>;

export function ClearStats():Promise<boolean>;

export function DownloadUpdate():Promise<void>;

export function GetAccountState():Promise<Record<string, any>>;

export function GetAnnouncement():Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetCodexRelayConfig():Promise<Record<string, any>>;

export function GetConfig():Promise<main.Config>;

export function GetDetectedPaths():Promise<main.DetectedPaths>;

export function GetFaqData():Promise<Record<string, any>>;

export function GetIDEStatus():Promise<main.IDEStatus>;

export function GetLogs():Promise<Array<string>>;

export function GetReferralInfo():Promise<Record<string, any>>;

export function GetStats():Promise<Record<string, any>>;

export function GetUpdateStatus():Promise<main.UpdateStatus>;

export function HeartbeatCheck():Promise<Record<string, any>>;

export function InjectSelected(arg1:Array<string>):Promise<string>;

export function InstallStandaloneClaude():Promise<void>;

export function IsHubRunningCheck():Promise<boolean>;

export function IsIDERunningCheck():Promise<boolean>;

export function LocalActivateGatewayTimeoutPreset(arg1:string):Promise<gatewaycfg.OpsConfig>;

export function LocalAddAntigravityApiKey(arg1:string,arg2:string,arg3:string):Promise<manager.AccountView>;

export function LocalAddAntigravitySwitchHistory(arg1:aghistory.SwitchHistoryItem):Promise<void>;

export function LocalAddAntigravityToken(arg1:string,arg2:string,arg3:string):Promise<manager.AccountView>;

export function LocalAddCodexApiKey(arg1:string,arg2:string,arg3:string):Promise<manager.AccountView>;

export function LocalAddCodexToken(arg1:string,arg2:string,arg3:string):Promise<manager.AccountView>;

export function LocalAntigravityAppFocus(arg1:string):Promise<void>;

export function LocalAntigravityAppRestart(arg1:string):Promise<void>;

export function LocalAntigravityAppStart(arg1:string):Promise<void>;

export function LocalAntigravityAppStop(arg1:string):Promise<void>;

export function LocalAntigravityApps():Promise<Array<hub.AntigravityAppView>>;

export function LocalAntigravityFocusDefault():Promise<void>;

export function LocalAntigravityGatewayStart():Promise<hub.GatewayStatus>;

export function LocalAntigravityGatewayStatus():Promise<hub.GatewayStatus>;

export function LocalAntigravityGatewayStop():Promise<void>;

export function LocalAntigravityRestartDefault():Promise<void>;

export function LocalAntigravityRuntimeStatus():Promise<boolean>;

export function LocalAntigravityStartDefault():Promise<void>;

export function LocalAntigravityStats():Promise<stats.Snapshot>;

export function LocalAntigravityStopDefault():Promise<void>;

export function LocalAntigravitySwitchHistory():Promise<Array<aghistory.SwitchHistoryItem>>;

export function LocalAntigravityWakeupClearVerificationHistory(arg1:Array<string>):Promise<number>;

export function LocalAntigravityWakeupConfig():Promise<wakeup.Config>;

export function LocalAntigravityWakeupHistory():Promise<Array<wakeup.RunEntry>>;

export function LocalAntigravityWakeupRunNow():Promise<Array<wakeup.RunEntry>>;

export function LocalAntigravityWakeupVerificationHistory():Promise<Array<wakeup.VerifyBatch>>;

export function LocalAntigravityWakeupVerificationState():Promise<Array<wakeup.VerifyResult>>;

export function LocalAntigravityWakeupVerifyBatch(arg1:Array<string>):Promise<wakeup.VerifyBatch>;

export function LocalAssignAccountsToGroup(arg1:string,arg2:Array<string>):Promise<accountgroups.Group>;

export function LocalBrowseForPath(arg1:string):Promise<string>;

export function LocalCancelAntigravityLogin(arg1:string):Promise<void>;

export function LocalCancelCodexLogin(arg1:string):Promise<void>;

export function LocalClearAntigravitySwitchHistory():Promise<void>;

export function LocalClearGatewayStats():Promise<void>;

export function LocalCodexReferralEligibility(arg1:string,arg2:string):Promise<codexbiz.ReferralInviteEligibility>;

export function LocalCodexReferralRules(arg1:string,arg2:string):Promise<codexbiz.ReferralEligibilityRules>;

export function LocalCodexSessionTokenStats(arg1:Array<string>):Promise<Array<sessionsync.SessionTokenStats>>;

export function LocalCodexStats():Promise<stats.Snapshot>;

export function LocalCodexWakeupClearVerificationHistory(arg1:Array<string>):Promise<number>;

export function LocalCodexWakeupConfig():Promise<wakeup.Config>;

export function LocalCodexWakeupHistory():Promise<Array<wakeup.RunEntry>>;

export function LocalCodexWakeupRunNow():Promise<Array<wakeup.RunEntry>>;

export function LocalCodexWakeupVerificationHistory():Promise<Array<wakeup.VerifyBatch>>;

export function LocalCodexWakeupVerificationState():Promise<Array<wakeup.VerifyResult>>;

export function LocalCodexWakeupVerifyBatch(arg1:Array<string>):Promise<wakeup.VerifyBatch>;

export function LocalConsumeCodexResetCredit(arg1:string,arg2:string):Promise<void>;

export function LocalCreateAccountGroup(arg1:string):Promise<accountgroups.Group>;

export function LocalCreateGatewayKey(arg1:string):Promise<gatewaykeys.Key>;

export function LocalCurrentAntigravityAccount():Promise<manager.AccountView>;

export function LocalCurrentCodexAccount():Promise<manager.AccountView>;

export function LocalDeleteAccount(arg1:string):Promise<void>;

export function LocalDeleteAccountGroup(arg1:string):Promise<void>;

export function LocalDeleteAccounts(arg1:Array<string>):Promise<void>;

export function LocalDeleteGatewayKey(arg1:string):Promise<void>;

export function LocalDeleteModelProvider(arg1:string):Promise<void>;

export function LocalDetectCodexAppPath():Promise<string>;

export function LocalEvaluateCodexAlert():Promise<economy.AlertResult>;

export function LocalExportAntigravityAccounts(arg1:Array<string>):Promise<string>;

export function LocalExportCodexAccounts(arg1:Array<string>):Promise<string>;

export function LocalGatewayConnTest():Promise<gateway.ConnTestResult>;

export function LocalGatewayStart():Promise<hub.GatewayStatus>;

export function LocalGatewayStatus():Promise<hub.GatewayStatus>;

export function LocalGatewayStop():Promise<void>;

export function LocalGetAlertConfig():Promise<economy.AlertConfig>;

export function LocalGetAntigravitySource():Promise<string>;

export function LocalGetAntigravityTarget():Promise<string>;

export function LocalGetAppSpeed():Promise<economy.AppSpeed>;

export function LocalGetCodexQuickConfig():Promise<codexsettings.QuickConfig>;

export function LocalGetCodexResetCredits(arg1:string):Promise<codexbiz.ResetCreditsSnapshot>;

export function LocalGetCodexSettings():Promise<codexsettings.Settings>;

export function LocalGetCodexSource():Promise<string>;

export function LocalGetGatewayAccessScope():Promise<string>;

export function LocalGetGatewayOpsConfig():Promise<gatewaycfg.OpsConfig>;

export function LocalGetRefreshConfig():Promise<refreshcfg.Config>;

export function LocalGetRoutingStrategy():Promise<string>;

export function LocalGetSwitchConfig():Promise<economy.SwitchConfig>;

export function LocalImportAntigravityAuthFiles(arg1:Array<string>):Promise<number>;

export function LocalImportAntigravityFromJSON(arg1:string):Promise<number>;

export function LocalImportCodexAuthFiles(arg1:Array<string>):Promise<number>;

export function LocalImportCodexFromJSON(arg1:string):Promise<number>;

export function LocalImportCodexFromLocal():Promise<number>;

export function LocalListAccountGroups():Promise<Array<accountgroups.Group>>;

export function LocalListAntigravityAccounts():Promise<Array<manager.AccountView>>;

export function LocalListCodexAccounts():Promise<Array<manager.AccountView>>;

export function LocalListCodexSessions(arg1:string,arg2:string):Promise<Array<sessionsync.SessionRecord>>;

export function LocalListGatewayKeys():Promise<Array<gatewaykeys.Key>>;

export function LocalListModelProviderModels(arg1:string):Promise<modelprovider.ListModelsResult>;

export function LocalListModelProviders():Promise<Array<modelprovider.Provider>>;

export function LocalListTrashedCodexSessions():Promise<Array<sessionsync.TrashedSessionRecord>>;

export function LocalMoveCodexSessionsToTrash(arg1:Array<string>):Promise<sessionsync.TrashSummary>;

export function LocalOpenCodexConfigToml():Promise<void>;

export function LocalQueryGatewayLogs(arg1:number,arg2:number,arg3:string):Promise<stats.LogPage>;

export function LocalRefreshAccountQuota(arg1:string):Promise<void>;

export function LocalRefreshAllQuotas(arg1:string):Promise<number>;

export function LocalRefreshCodexSubscription(arg1:string):Promise<codexbiz.SubscriptionSnapshot>;

export function LocalRemoveAccountsFromGroup(arg1:string,arg2:Array<string>):Promise<accountgroups.Group>;

export function LocalRenameAccount(arg1:string,arg2:string):Promise<void>;

export function LocalRenameAccountGroup(arg1:string,arg2:string):Promise<accountgroups.Group>;

export function LocalReorderAntigravityAccounts(arg1:Array<string>):Promise<void>;

export function LocalReorderCodexAccounts(arg1:Array<string>):Promise<void>;

export function LocalResolveAccountGroups():Promise<Record<string, string>>;

export function LocalRestoreCodexSessionsFromTrash(arg1:Array<string>):Promise<sessionsync.RestoreSummary>;

export function LocalRotateGatewayKey(arg1:string):Promise<gatewaykeys.Key>;

export function LocalSaveCodexQuickConfig(arg1:any,arg2:any):Promise<codexsettings.QuickConfig>;

export function LocalSaveCodexSettings(arg1:codexsettings.Settings):Promise<codexsettings.Settings>;

export function LocalSaveGatewayTimeoutPresets(arg1:Array<gatewaycfg.TimeoutPreset>):Promise<gatewaycfg.OpsConfig>;

export function LocalSaveGatewayTimeouts(arg1:gatewaycfg.Timeouts):Promise<gatewaycfg.OpsConfig>;

export function LocalSaveGatewayUpstreamProxy(arg1:string):Promise<gatewaycfg.OpsConfig>;

export function LocalSaveModelProvider(arg1:modelprovider.Provider):Promise<modelprovider.Provider>;

export function LocalSendCodexReferralInvites(arg1:string,arg2:string,arg3:Array<string>):Promise<codexbiz.ReferralInviteResponse>;

export function LocalSetAccountNote(arg1:string,arg2:string):Promise<void>;

export function LocalSetAccountTags(arg1:string,arg2:Array<string>):Promise<void>;

export function LocalSetAlertConfig(arg1:economy.AlertConfig):Promise<economy.AlertConfig>;

export function LocalSetAntigravityPriority(arg1:string):Promise<void>;

export function LocalSetAntigravitySource(arg1:string):Promise<void>;

export function LocalSetAntigravityTarget(arg1:string):Promise<void>;

export function LocalSetAntigravityWakeupConfig(arg1:boolean,arg2:number):Promise<void>;

export function LocalSetAppSpeed(arg1:economy.AppSpeed):Promise<economy.AppSpeed>;

export function LocalSetCodexAccountServiceTier(arg1:string,arg2:string):Promise<void>;

export function LocalSetCodexPriority(arg1:string):Promise<void>;

export function LocalSetCodexSource(arg1:string):Promise<void>;

export function LocalSetCodexWakeupConfig(arg1:boolean,arg2:number):Promise<void>;

export function LocalSetCurrentAntigravityAccount(arg1:string):Promise<void>;

export function LocalSetCurrentCodexAccount(arg1:string):Promise<void>;

export function LocalSetGatewayAccessScope(arg1:string):Promise<void>;

export function LocalSetGatewayPort(arg1:number):Promise<hub.GatewayStatus>;

export function LocalSetPoolEnabled(arg1:string,arg2:boolean):Promise<void>;

export function LocalSetRefreshConfig(arg1:number,arg2:number):Promise<refreshcfg.Config>;

export function LocalSetRoutingStrategy(arg1:string):Promise<void>;

export function LocalSetSwitchConfig(arg1:economy.SwitchConfig):Promise<economy.SwitchConfig>;

export function LocalStartAntigravityLogin():Promise<string>;

export function LocalStartCodexLogin():Promise<string>;

export function LocalSubmitAntigravityLoginCallback(arg1:string,arg2:string):Promise<void>;

export function LocalSubmitCodexLoginCallback(arg1:string,arg2:string):Promise<void>;

export function LocalSyncAntigravityFromIDE():Promise<number>;

export function LocalTestModelProvider(arg1:string):Promise<modelprovider.ConnTestResult>;

export function LocalUpdateAccountGroupSortOrder(arg1:string,arg2:number):Promise<accountgroups.Group>;

export function LocalWaitAntigravityLogin(arg1:string):Promise<manager.AccountView>;

export function LocalWaitCodexLogin(arg1:string):Promise<manager.AccountView>;

export function LocalWakeupTestOne(arg1:string):Promise<wakeup.VerifyResult>;

export function OpenCACertForTrust():Promise<void>;

export function OpenSystemPermissionSettings():Promise<void>;

export function RefreshQuota():Promise<void>;

export function RestartProxy():Promise<void>;

export function RestartToUpdate():Promise<void>;

export function RestoreSelected(arg1:Array<string>):Promise<string>;

export function SaveCodexRelayConfig(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Record<string, string>):Promise<void>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function SetClaudeDesktopMockLogin(arg1:boolean):Promise<boolean>;

export function SetSubscriptionPriority(arg1:string,arg2:number):Promise<void>;

export function UserLogin(arg1:string,arg2:string):Promise<Record<string, any>>;

export function UserLogout():Promise<void>;
